### ISSUE TITLE
Add support for custom WSAPI as implicit argument

### ISSUE THREAD

**Issue by hmvien** [codacy/scala-consul#14]
The default WSAPI requires an instance of a Play application which isn't available for all applications. I'll give this issue a try when I get a chance.

**Comment by jsw** [comment]
I'm using a custom play ApplicationLoader, and have the same or similar issue. At runtime I get a 

java.lang.InstantiationException: play.api.libs.ws.WSAPI

**Comment by mrfyda** [comment]
Since version 2.0.1, a WSClient can be injected no longer requiring a Play application.
