### ISSUE TITLE
Error: There is no started application

### ISSUE THREAD

**Issue by Wouter-M** [codacy/scala-consul#15]
Am I missing something or does this library not work without the Play framework? When I try to do something basic (adding a kv entry) I get this exception thrown at me, which seems to be an exception of the Play Framework:

```
java.lang.RuntimeException: There is no started application
```

Using the following code snippet:

``` scala
import java.net.InetAddress

import scala.concurrent.duration.Duration
import scala.concurrent.{Await, ExecutionContext}
import scala.concurrent._
import ExecutionContext.Implicits.global

object FailMain extends App {
  val cConsul = new consul.Consul(CONSUL_IP, CONSUL_PORT)
  import cConsul.v1._

  val fut = kv.put("testKey", "testValue")
  Await.result(fut, Duration("10 seconds"))
}
```

**Comment by johannegger** [comment]
Hi @Wouter-M ! 

thank you for your feedback. Yes you are right and that's a bummer. 
If you are interested the problem imho is in line 43 of https://github.com/codacy/scala-consul/blob/master/src/main/scala/consul/v1/common/ConsulRequestBasics.scala
where we call WS.url. I will try to find some time to refactor it but i can't tell you until when. in the mean time feel free to do a pull request and I will review it. 

Thank you!

**Comment by joshreuben123** [comment]
👎

**Comment by mrfyda** [comment]
Since version 2.0.1, a WSClient can be injected no longer requiring a Play application.
