### ISSUE TITLE
Support for play-ws and play-json 2.5.x

### ISSUE THREAD

**Issue by dbuschman7** [codacy/scala-consul#18]
What is your roadmap to upgrade this library to the play-\* 2.5.x versions?

**Comment by pedrorijo91** [comment]
Hey @dbuschman7,

At this moment we are not actively developing for this library. However, we are maintaining it, and we do accept community pull requests. If you are interested in upgrading this library, please let us know. We will help you in everything we can, but right now we do not have the time to develop it on our own

**Comment by dbuschman7** [comment]
Ok, I will find some time here to get a PR in.

**Comment by rtfpessoa** [comment]
This library is not maintained anymore.
