### ISSUE TITLE
Unable to Register scala service in consul 

### ISSUE THREAD

**Issue by JeetuChoudhary** [codacy/scala-consul#24]
Hello,
I want to register scala service in consul. I am using scala-consul sdk to do so. I am using following code for registration:
```
//for scala-consul
val myConsul = new consul.Consul(InetAddress.getByName("X.X.X.X").asInstanceOf[Inet4Address],8500)
import myConsul.v1._
val myAddress = "127.0.0.1"
val myServicePort = 2552
val myServiceCheck = agent.service.httpCheck("http://0.0.0.0:2552/health","15s")
println("servicecheck:"+myServiceCheck)
val myService = agent.service.LocalService(ServiceId("myServiceId"),ServiceType("myTypeOfService"),Set(ServiceTag("MyTag")),Some(myServicePort),Some(myServiceCheck))
val status=agent.service.register(myService)
status.onComplete {
    case Success(value) => println(s"Got the callback = $value")
    case Failure(e) => e.printStackTrace
  }
```
But I am getting Exception:
"Caused by: java.lang.RuntimeException: There is no started application"

it seems a bug in library because i am following same step as mentioned in documentation

**Comment by pedrorijo91** [comment]
Sorry @JeetuChoudhary  but this lib is currently unmaintained. Feel free to fork or offer as a maintainer

Other alternative libs seem to start getting well accepted in the community, just have a look at [helm](https://github.com/Verizon/helm) for instance

**Comment by rtfpessoa** [comment]
This library is not supported anymore.
