### ISSUE TITLE
How to use scala-consul 2.0.2

### ISSUE THREAD

**Issue by tusharmaini** [codacy/scala-consul#25]
I am trying to use scala-consul  2.0.2 which uses WS CLient as an input parameter, where can I find a usage example for the the same.

**Comment by pnerg** [comment]
I ran into the same problem. Not using Play and not really interested in fiddling with WS providers.
My solution was simply to use the standalone variant.
```scala
val consul = Consul.standalone(InetAddress.getByName("localhost"), 8500, None)
import consul.v1._
val services = catalog.services(None)
```

I'm however a bit dubious about this library as it seems to be a bit of abandonware according to #18 .

**Comment by pedrorijo91** [comment]
Sorry @tusharmaini @pnerg  but this lib is currently unmaintained. Feel free to fork or offer as a maintainer

Other alternative libs seem to start getting well accepted in the community, just have a look at [helm](https://github.com/Verizon/helm) for instance

**Comment by rtfpessoa** [comment]
This library is not supported anymore.
