### ISSUE TITLE
Maintaining this project

### ISSUE THREAD

**Issue by softinio** [codacy/scala-consul#27]
Noticed that this project is no longer maintained. 

I would be interested in taking it over and maintaining it as we do use consul. 

Many thanks.

**Comment by grouzen** [comment]
Yeah, this repo needs a maintainer ;)

**Comment by grouzen** [comment]
Seems like it's time to fork some code...

**Comment by rtfpessoa** [comment]
@grouzen Feel free to fork this and start working on it.

I think you could also consider other alternatives like:
* https://github.com/verizon/helm
* https://github.com/dlouwers/reactive-consul
* https://github.com/BoomTownROI/scala-consul

**Comment by rtfpessoa** [comment]
This library is not supported anymore.
