### ISSUE TITLE
Add support for index

### ISSUE THREAD

**Issue by 13h3r** [codacy/scala-consul#7]
Need to add support for `index` querying and blocking queues

**Comment by pedrorijo91** [comment]
Can you give more details please?

**Comment by 13h3r** [comment]
Check here - https://www.consul.io/docs/agent/http.html

**Comment by devth** [comment]
:+1: 

From the docs:

> Any endpoint that supports blocking will also set the HTTP header X-Consul-Index, a unique identifier representing the current state of the requested resource. On subsequent requests for this resource, the client can set the index query string parameter to the value of X-Consul-Index, indicating that the client wishes to wait for any changes subsequent to that index.
> 
> In addition to index, endpoints that support blocking will also honor a wait parameter specifying a maximum duration for the blocking request. This is limited to 10 minutes. If not set, the wait time defaults to 5 minutes. This value can be specified in the form of "10s" or "5m" (i.e., 10 seconds or 5 minutes, respectively).

This lets you essentially watch for new values for a given key. The nodejs lib implements it like this: https://github.com/silas/node-consul/blob/master/lib/watch.js

If it helps, here's the JS usage:

``` javascript
var config;

// watch
const watchConfig = consul.watch({
  method: consul.kv.get,
  options: {key: '/config', recurse: true}});

watchConfig.on('change', function(data, res) {
  console.log('config updated', data);
  config = data;
});

watchConfig.on('error', function(err) {
  console.log('config error:', err);
});
```

**Comment by derjust** [comment]
https://github.com/dlouwers/reactive-consul also supports it out of the box

**Comment by l15k4** [comment]
Is anybody working on this one? Watching for value changes would be nifty

**Comment by pedrorijo91** [comment]
Sorry @13h3r  @l15k4 @derjust @devth  but this lib is currently unmaintained. Feel free to fork or offer as a maintainer

Other alternative libs seem to start getting well accepted in the community, just have a look at [helm](https://github.com/Verizon/helm) for instance

**Comment by rtfpessoa** [comment]
This library is not maintained anymore.
